webapp2/views/inbox.py
from flask import *
from hashlib import sha256
import pdfkit
import urllib

from ..model import db, User, Certificate, Message
from ..config import SETTINGS
from .. import sec

inbox = Blueprint('inbox', __name__)


@inbox.before_request
def validate_user():
    if not session.get('in', False):
        return redirect(url_for('index'))

    request.user = User.query.filter_by(id=session['user_id']).first()


@inbox.route("/")
def index():
    messages = Message.query.filter_by(
        owner=request.user, postbox='inbox').all()
    messages = sorted(messages, reverse=True, key=lambda m: m.sent_date)
    return render_template("inbox/index.html", messages=messages)


@inbox.route("/sent")
def sent():
    messages = Message.query.filter_by(
        owner=request.user, postbox='sent').all()
    messages = sorted(messages, reverse=True, key=lambda m: m.sent_date)
    return render_template("inbox/sent.html", messages=messages)


@inbox.route("/deleted")
def deleted():
    messages = Message.query.filter_by(owner=request.user, postbox='deleted_inbox').all(
    ) + Message.query.filter_by(owner=request.user, postbox='deleted_sent').all()
    messages = sorted(messages, reverse=True, key=lambda m: m.sent_date)
    return render_template("inbox/deleted.html", messages=messages)


@inbox.route("/<id>")
def message(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    is_opened = m.is_opened

    m.is_seen = m.is_opened = True
    m.subject = message.Subject
    db.session.add(m)
    db.session.commit()

    if not is_opened:
        read_confirm(m, message, 'DECRYPTED')

    return render_template("inbox/message.html", id=id,
                           message=message, mobj=m)


@inbox.route("/<id>/pdf")
def message_pdf(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    if message.DataType == "text/raw":
        html = render_template("content-types/text.html",
                               message=message, safe_decode=safe_decode)
    elif message.DataType == "text/html":
        html = render_template("content-types/html.html", message=message)
    elif message.DataType == "application/pdf":
        http_response = make_response(message.Body)
        http_response.headers["Content-Type"] = "application/pdf"
        return http_response
    else:
        html = render_template("content-types/unknown.html", message=message)

    pdf = pdfkit.from_string(html, False, options={
        "title": message.Subject,
        'margin-top': '20mm',
        'margin-right': '25mm',
        'margin-bottom': '20mm',
        'margin-left': '25mm',
        'encoding': "UTF-8",
        'quiet': ''
    })

    http_response = make_response(pdf)
    http_response.headers["Content-Type"] = "application/pdf"

    is_read = m.is_read

    m.is_read = True
    db.session.add(m)
    db.session.commit()

    if not is_read:
        read_confirm(m, message, 'READ')

    return http_response


@inbox.route("/<id>/tds", methods=["GET", "POST"])
def tds(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()

    if request.method == 'POST':
        CONVERSIONS = {
            'inbox': 'deleted_inbox',
            'deleted_inbox': 'inbox',
            'sent': 'deleted_sent',
            'deleted_sent': 'sent',
        }
        m.postbox = CONVERSIONS[m.postbox]
        db.session.add(m)
        db.session.commit()

        return redirect(url_for('inbox.message', id=id))

    return render_template('inbox/tds.html', m=m)


@inbox.route("/<id>/ultimdel", methods=["GET", "POST"])
def ultimdel(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()

    if m.postbox in ['deleted_inbox', 'deleted_sent']:
        db.session.delete(m)
        db.session.commit()

        return redirect(url_for('inbox.deleted'))

    abort(403)


def safe_decode(txt):
    txt = txt.decode('utf-8').replace('<', '&lt;').replace('>', '&gt;')
    txt = txt.replace('&', '&quot;').replace(
        "\r\n", "\n").replace("\n\r", "\n")
    txt = txt.replace("\r", "\n")
    while "\n\n\n" in txt:
        txt = txt.replace("\n\n\n", "\n\n")
    txt = txt.replace('\n\n', '</p><p>').replace('\n', '<br>')

    return txt


def read_confirm(m, message, status):
    if m.origin_id:
        return None

    to_handle, to_server = message.Author.split('@')

    req = urllib.request.Request(
        "http://" + to_server + "/api/user/" + to_handle + "/confirm")
    req.method = "POST"
    req.data = (status + "\n" + str(m.id)).encode("utf-8")
    try:
        with urllib.request.urlopen(req) as res:
            response = res.read().decode("utf-8")
        return True
    except:
        return False

webapp2/views/send.py
from flask import *
from datetime import datetime
import urllib

from ..model import db, User, Certificate, Message
from ..config import SETTINGS
from .. import sec

send = Blueprint('send', __name__)


@send.before_request
def validate_user():
    if not session.get('in', False):
        return redirect(url_for('index'))

    request.user = User.query.filter_by(id=session['user_id']).first()


@send.route("/")
def index():
    return render_template("send/index.html")


@send.route("/forward/<id>")
def forward(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    return render_template("send/forward.html", id=id, message=message, mobj=m)


@send.route("/", methods=["POST"])
def it():
    to, subject, content_type = request.form['recipient'], request.form['subject'], request.form['content-type']

    if content_type == 'text/raw':
        body = request.form['body_raw'].encode('utf-8')
    elif content_type == 'text/html':
        body = request.form['body_html'].encode('utf-8')
    elif content_type == 'application/pdf':
        body = request.files['body_pdf'].read()
    else:
        body = request.form['body'].encode('utf-8')

    c = Certificate.query.filter_by(full_handle=to).first()
    own_cert = sec.CertFile.parse(
        request.user.certificate.certfile_body).cert()
    to_handle, to_server = to.split('@')

    if c is None:
        try:
            with urllib.request.urlopen("http://" + to_server + "/api/user/" + to_handle + "/certfile") as tc:
                to_cert = tc.read().decode("utf-8")
            original_cert = to_cert
            to_certfile = sec.CertFile.parse(to_cert)
            to_cert = to_certfile.cert()
        except SyntaxError:
            return render_template(
                "send/done.html",
                code="ERROR",
                comment="Verschlüsselungszertifikat nicht erreichbar.")

        trustlist = SETTINGS['trustlist']

        if to_server not in trustlist:
            try:
                with urllib.request.urlopen("http://" + to_server + "/api/certfile") as tsc:
                    to_service_cert = tsc.read().decode("utf-8")
                to_service_certfile = sec.CertFile.parse(
                    to_service_cert)
                to_service_cert = to_service_certfile.cert()
            except SyntaxError:
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat des Anbieters des Empfängers nicht erreichbar.")

            if not to_service_certfile.verify():
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat des Anbieters des Empfängers spezifikationswidrig nicht eigensigniert.")

            if not to_certfile.verify(to_service_cert):
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat Empfängers nicht ordnungsgemäß signiert.")

        c = Certificate()
        c.name = to_cert.Name
        c.full_handle = to_handle + '@' + to_server
        c.certfile_body = original_cert
        c.is_validated = True

        db.session.add(c)
        db.session.commit()

    user_privkey_sign = sec.inputPrivateKey(
        request.user.private_sign_key.encode("utf-8"), session['password'])

    recipient_cert = sec.CertFile.parse(c.certfile_body).cert()

    origm = sec.Message(subject, content_type, body,
                        own_cert, recipient_cert, datetime.now())
    m = origm.encrypt(recipient_cert)
    m_code = m.build_signed(user_privkey_sign)

    req = urllib.request.Request(
        "http://" + to_server + "/api/user/" + to_handle + "/recv")
    req.method = "POST"
    req.data = m_code.encode("utf-8")
    try:
        with urllib.request.urlopen(req) as res:
            response = res.read().decode("utf-8")
    except BaseException:
        response = "ERROR\nServer-Fehler"

    code, comment = response.split("\n", maxsplit=1)

    if code == 'OK':
        own_m = origm.encrypt(own_cert)
        own_m = own_m.build_signed(user_privkey_sign)

        m = Message()
        m.postbox = 'sent'
        m.author = c
        m.owner = request.user
        m.message_body = own_m
        m.subject = origm.Subject
        m.is_seen = m.is_read = False
        m.is_opened = True
        m.origin_id = comment
        m.sent_date = origm.MessageDate
        db.session.add(m)
        db.session.commit()

    return render_template("send/done.html", code=code, comment=comment)


@send.route("/forward/<id>", methods=["POST"])
def forward_it(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    request.form = request.form.copy()

    request.form['body'] = request.form['body_html'] = request.form['body_raw'] = message.Body.decode(
        "utf-8")
    request.form['content-type'] = message.DataType

    return it()

webapp2/templates/send/done.html
{% extends "layout/application.html" %}
{% block body %}

{% if code == "OK" %}
<h1>Nachricht gesendet!</h1>
<p>Die Nachricht wurde erfolgreich abgesendet.</p>
<a href="{{ url_for('inbox.sent') }}" class="button">Gesendete Nachrichten anzeigen</a>
<a href="{{ url_for('inbox.index') }}" class="button">Posteingang anzeigen</a>
{% else %}
<h1>Uups.</h1>
<p>Die Nachricht wurde offenbar nicht angenommen.</p>
<a href="javascript:window.location.reload()" class="button secondary">Erneut versuchen</a>
<p>Der Server meldet:</p>
<pre><code><strong>{{ code }}:</strong> {{ comment }}</code></pre>
{% endif %}

{% endblock %}

webapp2/templates/send/forward.html
{% extends "layout/application.html" %}
{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename='quill/quill.snow.css') }}"></script>
<script src="{{ url_for('static', filename='quill/quill.js') }}"></script>

<form action="{{ url_for('send.forward_it', id=mobj.id) }}" method="POST">
    <button type="submit" class="button is-right-btn">Nachricht absenden</button>
    <a href="{{ url_for('inbox.message', id=mobj.id) }}" class="button secondary is-right-btn">Abbrechen</a>
    <h1>Nachricht weiterleiten</h1>

    <label for="recipient">Empfänger</label>
    <input id="recipient" name="recipient" placeholder="kennung@server">

    <label for="subject">Betreff</label>
    <input id="subject" name="subject" value="Fwd: {{ mobj.subject }}">

    <p>Leite nur Nachrichten weiter, wenn du dazu berechtigt bist oder die andere Person dies erwartet.</p>
</form>
{% endblock %}

webapp2/templates/send/index.html
{% extends "layout/application.html" %}
{% block body %}
<link rel="stylesheet" href="{{ url_for('static', filename='quill/quill.snow.css') }}"></script>
<script src="{{ url_for('static', filename='quill/quill.js') }}"></script>

<form action="{{ url_for('send.it') }}" method="POST">
    <button type="submit" class="button is-right-btn">Nachricht absenden</button>
    <a href="{{ url_for('inbox.index') }}" class="button secondary is-right-btn">Abbrechen</a>
    <h1>Nachricht senden</h1>

    <label for="recipient">Empfänger</label>
    <input id="recipient" name="recipient" placeholder="kennung@server" value="{{ request.values.get('reply_to', '') }}">

    <label for="subject">Betreff</label>
    <input id="subject" name="subject" value="{{ request.values.get('subject', '') }}">

    <div class="folders doctype--selection">
        <a href="javascript:selectDTP('text/raw')" data-dt="text/raw">Unformattierter Text</a>
        <a href="javascript:selectDTP('text/html')" data-dt="text/html" class="current">Normaler Text</a>
        <a href="javascript:selectDTP('application/pdf')" data-dt="application/pdf" >PDF Hochladen</a>
    </div>

    <input type="hidden" name="content-type" id="content-type" value="text/html">

    <div class="doctype--partial is-raw">
        <textarea id="body_raw" name="body_raw"></textarea>
    </div>

    <div class="doctype--partial is-html is-active">
        <div id="body_html"></div>
        <input type="hidden" name="body_html" id="body_html-input">
    </div>

    <div class="doctype--partial is-pdf">
        <p>Wähle die PDF-Datei aus:</p>
        <input type="file" name="body_pdf" accept="pdf">
    </div>


    <script>
        var quill = new Quill('#body_html', {
            theme: 'snow',
            placeholder: 'Nachricht schreiben...',
            modules: {
                toolbar: [
                    ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
                    [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
                    [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown

                    [{ 'header': 1 }, { 'header': 2 }],               // custom button values
                    [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
                    
                    [{ 'align': [] }],

                    [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme

                    ['clean']                                         // remove formatting button
                ]
            }
        });

        quill.on('text-change', function(delta, oldDelta, source) {
            document.getElementById('body_html-input').value = document.querySelector('#body_html .ql-editor').innerHTML
        })


        function selectDTP(mime) {
            self = document.querySelector('[data-dt="'+mime+'"]');
            self.parentNode.querySelector('.current').classList.remove('current');
            self.classList.add('current');

            document.querySelector('#content-type').value = mime;

            if(document.querySelector('.doctype--partial.is-active'))
                document.querySelector('.doctype--partial.is-active').classList.remove('is-active');

            form = document.querySelector('form');
            form.removeAttribute('enctype');

            if(mime == "text/raw") {
                document.querySelector('.doctype--partial.is-raw').classList.add('is-active');
            } else if (mime == "text/html") {
                document.querySelector('.doctype--partial.is-html').classList.add('is-active');
            } else if (mime == "application/pdf") {
                document.querySelector('.doctype--partial.is-pdf').classList.add('is-active');
            form.setAttribute('enctype', 'multipart/form-data');
            }
        }
    </script>
</form>
{% endblock %}