webapp2/views/inbox.py
from flask import *
from hashlib import sha256
import pdfkit
import urllib

from ..model import db, User, Certificate, Message
from ..config import SETTINGS
from .. import sec

inbox = Blueprint('inbox', __name__)


@inbox.before_request
def validate_user():
    if not session.get('in', False):
        return redirect(url_for('index'))

    request.user = User.query.filter_by(id=session['user_id']).first()


@inbox.route("/")
def index():
    messages = Message.query.filter_by(
        owner=request.user, postbox='inbox').all()
    messages = sorted(messages, reverse=True, key=lambda m: m.sent_date)
    return render_template("inbox/index.html", messages=messages)


@inbox.route("/sent")
def sent():
    messages = Message.query.filter_by(
        owner=request.user, postbox='sent').all()
    messages = sorted(messages, reverse=True, key=lambda m: m.sent_date)
    return render_template("inbox/sent.html", messages=messages)


@inbox.route("/deleted")
def deleted():
    messages = Message.query.filter_by(owner=request.user, postbox='deleted_inbox').all(
    ) + Message.query.filter_by(owner=request.user, postbox='deleted_sent').all()
    messages = sorted(messages, reverse=True, key=lambda m: m.sent_date)
    return render_template("inbox/deleted.html", messages=messages)


@inbox.route("/<id>")
def message(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    is_opened = m.is_opened

    m.is_seen = m.is_opened = True
    m.subject = message.Subject
    db.session.add(m)
    db.session.commit()

    if not is_opened:
        read_confirm(m, message, 'DECRYPTED')

    return render_template("inbox/message.html", id=id,
                           message=message, mobj=m)


@inbox.route("/<id>/pdf")
def message_pdf(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    if message.DataType == "text/raw":
        html = render_template("content-types/text.html",
                               message=message, safe_decode=safe_decode)
    elif message.DataType == "text/html":
        html = render_template("content-types/html.html", message=message)
    elif message.DataType == "application/pdf":
        http_response = make_response(message.Body)
        http_response.headers["Content-Type"] = "application/pdf"
        return http_response
    else:
        html = render_template("content-types/unknown.html", message=message)

    pdf = pdfkit.from_string(html, False, options={
        "title": message.Subject,
        'margin-top': '20mm',
        'margin-right': '25mm',
        'margin-bottom': '20mm',
        'margin-left': '25mm',
        'encoding': "UTF-8",
        'quiet': ''
    })

    http_response = make_response(pdf)
    http_response.headers["Content-Type"] = "application/pdf"

    is_read = m.is_read

    m.is_read = True
    db.session.add(m)
    db.session.commit()

    if not is_read:
        read_confirm(m, message, 'READ')

    return http_response


@inbox.route("/<id>/tds", methods=["GET", "POST"])
def tds(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()

    if request.method == 'POST':
        CONVERSIONS = {
            'inbox': 'deleted_inbox',
            'deleted_inbox': 'inbox',
            'sent': 'deleted_sent',
            'deleted_sent': 'sent',
        }
        m.postbox = CONVERSIONS[m.postbox]
        db.session.add(m)
        db.session.commit()

        return redirect(url_for('inbox.message', id=id))

    return render_template('inbox/tds.html', m=m)


@inbox.route("/<id>/ultimdel", methods=["GET", "POST"])
def ultimdel(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()

    if m.postbox in ['deleted_inbox', 'deleted_sent']:
        db.session.delete(m)
        db.session.commit()

        return redirect(url_for('inbox.deleted'))

    abort(403)


def safe_decode(txt):
    txt = txt.decode('utf-8').replace('<', '&lt;').replace('>', '&gt;')
    txt = txt.replace('&', '&quot;').replace(
        "\r\n", "\n").replace("\n\r", "\n")
    txt = txt.replace("\r", "\n")
    while "\n\n\n" in txt:
        txt = txt.replace("\n\n\n", "\n\n")
    txt = txt.replace('\n\n', '</p><p>').replace('\n', '<br>')

    return txt


def read_confirm(m, message, status):
    if m.origin_id:
        return None

    to_handle, to_server = message.Author.split('@')

    req = urllib.request.Request(
        "http://" + to_server + "/api/user/" + to_handle + "/confirm")
    req.method = "POST"
    req.data = (status + "\n" + str(m.id)).encode("utf-8")
    try:
        with urllib.request.urlopen(req) as res:
            response = res.read().decode("utf-8")
        return True
    except:
        return False

webapp2/views/send.py
from flask import *
from datetime import datetime
import urllib

from ..model import db, User, Certificate, Message
from ..config import SETTINGS
from .. import sec

send = Blueprint('send', __name__)


@send.before_request
def validate_user():
    if not session.get('in', False):
        return redirect(url_for('index'))

    request.user = User.query.filter_by(id=session['user_id']).first()


@send.route("/")
def index():
    return render_template("send/index.html")


@send.route("/forward/<id>")
def forward(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    return render_template("send/forward.html", id=id, message=message, mobj=m)


@send.route("/", methods=["POST"])
def it():
    to, subject, content_type = request.form['recipient'], request.form['subject'], request.form['content-type']

    if content_type == 'text/raw':
        body = request.form['body_raw'].encode('utf-8')
    elif content_type == 'text/html':
        body = request.form['body_html'].encode('utf-8')
    elif content_type == 'application/pdf':
        body = request.files['body_pdf'].read()
    else:
        body = request.form['body'].encode('utf-8')

    c = Certificate.query.filter_by(full_handle=to).first()
    own_cert = sec.CertFile.parse(
        request.user.certificate.certfile_body).cert()
    to_handle, to_server = to.split('@')

    if c is None:
        try:
            with urllib.request.urlopen("http://" + to_server + "/api/user/" + to_handle + "/certfile") as tc:
                to_cert = tc.read().decode("utf-8")
            original_cert = to_cert
            to_certfile = sec.CertFile.parse(to_cert)
            to_cert = to_certfile.cert()
        except SyntaxError:
            return render_template(
                "send/done.html",
                code="ERROR",
                comment="Verschlüsselungszertifikat nicht erreichbar.")

        trustlist = SETTINGS['trustlist']

        if to_server not in trustlist:
            try:
                with urllib.request.urlopen("http://" + to_server + "/api/certfile") as tsc:
                    to_service_cert = tsc.read().decode("utf-8")
                to_service_certfile = sec.CertFile.parse(
                    to_service_cert)
                to_service_cert = to_service_certfile.cert()
            except SyntaxError:
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat des Anbieters des Empfängers nicht erreichbar.")

            if not to_service_certfile.verify():
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat des Anbieters des Empfängers spezifikationswidrig nicht eigensigniert.")

            if not to_certfile.verify(to_service_cert):
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat Empfängers nicht ordnungsgemäß signiert.")

        c = Certificate()
        c.name = to_cert.Name
        c.full_handle = to_handle + '@' + to_server
        c.certfile_body = original_cert
        c.is_validated = True

        db.session.add(c)
        db.session.commit()

    user_privkey_sign = sec.inputPrivateKey(
        request.user.private_sign_key.encode("utf-8"), session['password'])

    recipient_cert = sec.CertFile.parse(c.certfile_body).cert()

    origm = sec.Message(subject, content_type, body,
                        own_cert, recipient_cert, datetime.now())
    m = origm.encrypt(recipient_cert)
    m_code = m.build_signed(user_privkey_sign)

    req = urllib.request.Request(
        "http://" + to_server + "/api/user/" + to_handle + "/recv")
    req.method = "POST"
    req.data = m_code.encode("utf-8")
    try:
        with urllib.request.urlopen(req) as res:
            response = res.read().decode("utf-8")
    except BaseException:
        response = "ERROR\nServer-Fehler"

    code, comment = response.split("\n", maxsplit=1)

    if code == 'OK':
        own_m = origm.encrypt(own_cert)
        own_m = own_m.build_signed(user_privkey_sign)

        m = Message()
        m.postbox = 'sent'
        m.author = c
        m.owner = request.user
        m.message_body = own_m
        m.subject = origm.Subject
        m.is_seen = m.is_read = False
        m.is_opened = True
        m.origin_id = comment
        m.sent_date = origm.MessageDate
        db.session.add(m)
        db.session.commit()

    return render_template("send/done.html", code=code, comment=comment)


@send.route("/forward/<id>", methods=["POST"])
def forward_it(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    request.form = request.form.copy()

    request.form['body'] = request.form['body_html'] = request.form['body_raw'] = message.Body.decode(
        "utf-8")
    request.form['content-type'] = message.DataType

    return it()

webapp2/templates/inbox/_list.html
<div class="message-list">
    {% for message in messages %}
    <div class="message">
        {% if message.is_opened %}
        <h3><a href="{{ url_for('inbox.message', id=message.id) }}">{{ message.subject }}</a></h3>
        {% else %}
        <h3 class="unopened">🔒 <a href="{{ url_for('inbox.message', id=message.id) }}">Noch nicht geöffnet</a></h3>
        {% endif %}
        <div class="meta">
            <div class="meta--field">
                🕒 {{ message.sent_date }}
            </div>
            <div class="meta--field">
                👤 {{ message.author.name }}
            </div>
            <div class="meta--field">
                {{ message.author.full_handle }}
            </div>
            <div class="meta--field">
                📁 {{ {'inbox': 'Posteingang', 'sent': 'Gesendete Nachrichten', 'deleted_inbox': 'Gelöschte Nachrichten', 'deleted_sent': 'Gelöschte Nachrichten'}[message.postbox] }}
            </div>
        </div>
    </div>
    {% else %}
    <p>Leider noch keine Nachrichten in dieser Kategorie.</p>
    {% endfor %}
</div>

webapp2/templates/inbox/deleted.html
{% extends "layout/application.html" %}
{% block body %}
<a href="" class="button is-right-btn">Aktualisieren</a>
<a href="{{ url_for('send.index') }}" class="button secondary is-right-btn">Nachricht verfassen</a>
<h1>Gelöschte Nachrichten</h1>
<div class="folders">
    <a href="{{ url_for('inbox.index') }}">Posteingang</a>
    <a href="{{ url_for('inbox.sent') }}">Gesendete Nachrichten</a>
    <a href="{{ url_for('inbox.deleted') }}" class="current">Gelöschte Nachrichten</a>
</div>

{% include "inbox/_list.html" %}
{% endblock %}

webapp2/templates/inbox/index.html
{% extends "layout/application.html" %}
{% block body %}
<a href="" class="button is-right-btn">Aktualisieren</a>
<a href="{{ url_for('send.index') }}" class="button secondary is-right-btn">Nachricht verfassen</a>
<h1>Posteingang</h1>
<div class="folders">
    <a href="{{ url_for('inbox.index') }}" class="current">Posteingang</a>
    <a href="{{ url_for('inbox.sent') }}">Gesendete Nachrichten</a>
    <a href="{{ url_for('inbox.deleted') }}">Gelöschte Nachrichten</a>
</div>

{% include "inbox/_list.html" %}
{% endblock %}

webapp2/templates/inbox/message.html
{% extends "layout/application.html" %}
{% block body %}
<a href="{{ url_for('inbox.index') }}" class="nav-btn">&laquo; Zurück zum Posteingang</a>
<h1>{{ message.Subject }}</h1>
<div class="meta">
    <div class="meta--field">
        🕒 {{ mobj.sent_date }}
    </div>
    <div class="meta--field">
        👤 {{ mobj.author.name }}
    </div>
    <div class="meta--field">
        <a href="{{ url_for('contact.user', handle=mobj.author.full_handle) }}">{{ mobj.author.full_handle }}</a>
    </div>
    <div class="meta--field">
        📁 {{ {'inbox': 'Posteingang', 'sent': 'Gesendete Nachrichten', 'deleted_inbox': 'Gelöschte Nachrichten', 'deleted_sent': 'Gelöschte Nachrichten'}[mobj.postbox] }}
    </div>
</div>

<p>{% if mobj.postbox in ['inbox', 'sent'] %}
    <a href="{{ url_for('send.index', subject='Re: ' + message.Subject, reply_to=message.Author) }}" class="button">Antworten</a>
    <a href="{{ url_for('send.forward', id=mobj.id) }}" class="button secondary">Weiterleiten</a>
    <a href="{{ url_for('inbox.tds', id=mobj.id) }}" class="button secondary">Löschen</a>
{% else %}
    <a href="{{ url_for('inbox.tds', id=mobj.id) }}" class="button">Wiederherstellen</a>
    <a href="{{ url_for('inbox.ultimdel', id=mobj.id) }}" class="button secondary">Endgültig löschen</a>
{% endif %}</p>

{% if mobj.postbox not in ['inbox', 'sent'] %}
<div class="error">Die Nachricht wurde gelöscht. Du kannst sie aber wiederherstellen.</div>
{% else %}
<div id="pdf_view"></div>
<script src="{{ url_for('static', filename='pdfobject/pdfobject.min.js') }}"></script>
<script>PDFObject.embed("{{ url_for('inbox.message_pdf', id=mobj.id) }}", "#pdf_view",
                        { forcePDFJS: true, PDFJS_URL: "{{ url_for('static', filename='pdfjs/web/viewer.html') }}"});</script>
{% endif %}
{% if mobj.origin_id != None %}
<h3>Zustellstatus</h3>
<table>
    <tr>
        <th>Zeitpunkt?</th>
        <th>Status</th>
    </tr>
    {% for ev in mobj.message_event %}
    <tr>
        <td>{{ ev.event_date }}</td>
        <td>{% if ev.status == "STORED" %}
            <strong>Gespeichert.</strong>
            Die Nachricht wurde auf dem lokalen Server der Empfängerin/des Empfängers gespeichert.
            {% elif ev.status == "DECRYPTED" %}
            <strong>Entschlüsselt.</strong>
            Die Nachricht wurde erstmalig entschlüsselt.
            {% elif ev.status == "READ" %}
            <strong>Gelesen.</strong>
            Die Empfängerin/Der Empfänger hat die Nachricht geöffnet und gelesen.
            {% elif ev.status == "NOTIFIED" %}
            <strong>Benachrichtigt.</strong>
            Die Empfängerin/Der Empfänger wurde über die Nachricht informiert.
            {% else %}{{ ev.status }}{% endif %}
        </td>
    </tr>
    {% else %}
    <tr>
        <td colspan="2">Noch keine Ereignisse.</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}

webapp2/templates/inbox/sent.html
{% extends "layout/application.html" %}
{% block body %}
<a href="" class="button is-right-btn">Aktualisieren</a>
<a href="{{ url_for('send.index') }}" class="button secondary is-right-btn">Nachricht verfassen</a>
<h1>Gesendete Nachrichten</h1>
<div class="folders">
    <a href="{{ url_for('inbox.index') }}">Posteingang</a>
    <a href="{{ url_for('inbox.sent') }}" class="current">Gesendete Nachrichten</a>
    <a href="{{ url_for('inbox.deleted') }}">Gelöschte Nachrichten</a>
</div>

{% include "inbox/_list.html" %}
{% endblock %}

webapp2/templates/inbox/tds.html
{% extends "layout/application.html" %}
{% block body %}
<a href="{{ url_for('inbox.index') }}" class="nav-btn">&laquo; Zurück zum Posteingang</a>
<h1>{{ m.subject }}</h1>
<div class="meta">
    <div class="meta--field">
        🕒 {{ m.sent_date }}
    </div>
    <div class="meta--field">
        👤 {{ m.author.name }}
    </div>
    <div class="meta--field">
        {{ m.author.full_handle }}
    </div>
    <div class="meta--field">
        📁 {{ {'inbox': 'Posteingang', 'sent': 'Gesendete Nachrichten', 'deleted_inbox': 'Gelöschte Nachrichten', 'deleted_sent': 'Gelöschte Nachrichten'}[m.postbox] }}
    </div>
</div>

{% if m.postbox in ['inbox', 'sent'] %}
<p>Willst du diese Nachricht wirklich entfernen?</p>
{% else %}
<p>Willst du diese Nachricht wiederherstellen?</p>
{% endif %}

<form action="" method="POST">
    <button type="submit" class="button">Bestätigen</button>
    <a href="{{ url_for('inbox.message', id=m.id) }}" class="button secondary">Abbrechen</a>
</form>
{% endblock %}