webapp2/views/contact.py
from flask import *
from datetime import datetime
import urllib

from ..model import db, User, Certificate
from ..config import SETTINGS
from .. import sec

contact = Blueprint('contact', __name__)


@contact.before_request
def validate_user():
    if not session.get('in', False):
        return redirect(url_for('index'))

    request.user = User.query.filter_by(id=session['user_id']).first()


@contact.route("/<handle>")
def user(handle):
    cert = Certificate.query.filter_by(full_handle=handle).first_or_404()

    cert_handle, cert_server = handle.split('@')

    trust_status = 'neither_nor'

    try:
        with urllib.request.urlopen("http://" + cert_server + "/api/user/" +
                                    cert_handle + "/certfile") as tc:
            the_cert = tc.read().decode("utf-8")
        original_cert = the_cert
        the_certfile = sec.CertFile.parse(the_cert)
        the_cert = the_certfile.cert()
    except BaseException:
        print("TC not fetchable")
        trust_status = 'broken'

    if trust_status != 'broken':
        try:
            with urllib.request.urlopen("http://" + cert_server + "/api/certfile") as oc:
                origin_service_cert = oc.read().decode("utf-8")
                print('***' * 50)
            origin_service_certfile = sec.CertFile.parse(
                origin_service_cert)
            origin_service_cert = origin_service_certfile.cert()
        except BaseException:
            print("OSC not fetchable")
            trust_status = 'broken'

    if trust_status != 'broken':
        if not origin_service_certfile.verify():
            print("OSC not self-signed")
            trust_status = 'broken'

    if trust_status != 'broken':
        if not the_certfile.verify(origin_service_cert):
            trust_status = 'broken'
            print("TC not properly signed")
        else:
            trustlist = SETTINGS['trustlist']
            if cert_server == SETTINGS['SERVER_URL']:
                trust_status = 'local'
            elif cert_server in trustlist:
                trust_status = 'trustworthy_service'

    cf = sec.CertFile.parse(cert.certfile_body)
    sec_cert = cf.cert()

    if cert.certfile_body != original_cert:
        cert.certfile_body = original_cert
        db.session.add(cert)
        db.session.commit()

    return render_template("contact/user.html", cert=cert,
                           sec_cert=sec_cert, trust_status=trust_status)


@contact.route("/admin/<id>")
def admin_page(id):
    user = User.query.get_or_404(id)
    certificate = user.certificate
    certfile = sec.CertFile.parse(certificate.certfile_body)
    cert = certfile.cert()
    return render_template("contact/admin_page.html", user=user, cert=cert)


@contact.route("/admin/<id>", methods=["POST"])
def admin_update(id):
    user = User.query.get_or_404(id)

    server_cert = sec.CertFile.load("cert/server_cert.certfile")
    if not server_cert.verify():
        return {"errors": ["Serverfehler. Ungültiges Service-Zertifikat."]}
    server_cert = server_cert.cert()
    server_privkey_sign = sec.loadPrivateKey(
        "cert/server_cert", "sign",
        passphrase=SETTINGS['CERTIFICATE_ENCRYPTION'])

    certificate = user.certificate
    certfile = sec.CertFile.parse(certificate.certfile_body)
    cert = certfile.cert(server_cert)

    if 'verified' in cert.Flags:
        cert.Flags.remove('verified')
    if 'authority' in cert.Flags:
        cert.Flags.remove('authority')
    if 'readconfirm' in cert.Flags:
        cert.Flags.remove('readconfirm')

    if 'verified' in request.form.keys():
        cert.Flags.append('verified')
    if 'authority' in request.form.keys():
        cert.Flags.append('authority')

    if SETTINGS['CONFIRM_READ']:
        cert.Flags.append('readconfirm')

    cert_code = cert.build_signed(server_privkey_sign)

    certificate.certfile_body = cert_code
    db.session.add(certificate)
    db.session.commit()

    return redirect(url_for('contact.user', handle=certificate.full_handle))

webapp2/views/send.py
from flask import *
from datetime import datetime
import urllib

from ..model import db, User, Certificate, Message
from ..config import SETTINGS
from .. import sec

send = Blueprint('send', __name__)


@send.before_request
def validate_user():
    if not session.get('in', False):
        return redirect(url_for('index'))

    request.user = User.query.filter_by(id=session['user_id']).first()


@send.route("/")
def index():
    return render_template("send/index.html")


@send.route("/forward/<id>")
def forward(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    return render_template("send/forward.html", id=id, message=message, mobj=m)


@send.route("/", methods=["POST"])
def it():
    to, subject, content_type = request.form['recipient'], request.form['subject'], request.form['content-type']

    if content_type == 'text/raw':
        body = request.form['body_raw'].encode('utf-8')
    elif content_type == 'text/html':
        body = request.form['body_html'].encode('utf-8')
    elif content_type == 'application/pdf':
        body = request.files['body_pdf'].read()
    else:
        body = request.form['body'].encode('utf-8')

    c = Certificate.query.filter_by(full_handle=to).first()
    own_cert = sec.CertFile.parse(
        request.user.certificate.certfile_body).cert()
    to_handle, to_server = to.split('@')

    if c is None:
        try:
            with urllib.request.urlopen("http://" + to_server + "/api/user/" + to_handle + "/certfile") as tc:
                to_cert = tc.read().decode("utf-8")
            original_cert = to_cert
            to_certfile = sec.CertFile.parse(to_cert)
            to_cert = to_certfile.cert()
        except SyntaxError:
            return render_template(
                "send/done.html",
                code="ERROR",
                comment="Verschlüsselungszertifikat nicht erreichbar.")

        trustlist = SETTINGS['trustlist']

        if to_server not in trustlist:
            try:
                with urllib.request.urlopen("http://" + to_server + "/api/certfile") as tsc:
                    to_service_cert = tsc.read().decode("utf-8")
                to_service_certfile = sec.CertFile.parse(
                    to_service_cert)
                to_service_cert = to_service_certfile.cert()
            except SyntaxError:
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat des Anbieters des Empfängers nicht erreichbar.")

            if not to_service_certfile.verify():
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat des Anbieters des Empfängers spezifikationswidrig nicht eigensigniert.")

            if not to_certfile.verify(to_service_cert):
                return render_template(
                    "send/done.html",
                    code="ERROR",
                    comment="Verschlüsselungszertifikat Empfängers nicht ordnungsgemäß signiert.")

        c = Certificate()
        c.name = to_cert.Name
        c.full_handle = to_handle + '@' + to_server
        c.certfile_body = original_cert
        c.is_validated = True

        db.session.add(c)
        db.session.commit()

    user_privkey_sign = sec.inputPrivateKey(
        request.user.private_sign_key.encode("utf-8"), session['password'])

    recipient_cert = sec.CertFile.parse(c.certfile_body).cert()

    origm = sec.Message(subject, content_type, body,
                        own_cert, recipient_cert, datetime.now())
    m = origm.encrypt(recipient_cert)
    m_code = m.build_signed(user_privkey_sign)

    req = urllib.request.Request(
        "http://" + to_server + "/api/user/" + to_handle + "/recv")
    req.method = "POST"
    req.data = m_code.encode("utf-8")
    try:
        with urllib.request.urlopen(req) as res:
            response = res.read().decode("utf-8")
    except BaseException:
        response = "ERROR\nServer-Fehler"

    code, comment = response.split("\n", maxsplit=1)

    if code == 'OK':
        own_m = origm.encrypt(own_cert)
        own_m = own_m.build_signed(user_privkey_sign)

        m = Message()
        m.postbox = 'sent'
        m.author = c
        m.owner = request.user
        m.message_body = own_m
        m.subject = origm.Subject
        m.is_seen = m.is_read = False
        m.is_opened = True
        m.origin_id = comment
        m.sent_date = origm.MessageDate
        db.session.add(m)
        db.session.commit()

    return render_template("send/done.html", code=code, comment=comment)


@send.route("/forward/<id>", methods=["POST"])
def forward_it(id):
    m = Message.query.filter_by(owner=request.user, id=id).first_or_404()
    user_privkey_recv = sec.inputPrivateKey(
        request.user.private_recv_key.encode("utf-8"), session['password'])
    message_file = m.message_body

    message = sec.MessageLoader.parse(message_file)
    message = message.decrypt(user_privkey_recv)

    request.form = request.form.copy()

    request.form['body'] = request.form['body_html'] = request.form['body_raw'] = message.Body.decode(
        "utf-8")
    request.form['content-type'] = message.DataType

    return it()

webapp2/templates/contact/admin_page.html
{% extends "layout/application.html" %}
{% block body %}
<h1>{{ user.username }}</h1>

<form action="{{ url_for('contact.admin_update', id=user.id) }}" method="post">
    <h3>Attribute setzen</h3>

    <label for="verified">Verifiziert.</label>
    <input type="checkbox" id="verified" name="verified" value="verified" {{ 'checked' if 'verified' in cert.Flags }}>

    <label for="authority">Amtlich.</label>
    <input type="checkbox" id="authority" name="authority" value="authority" {{ 'checked' if 'authority' in cert.Flags }}>

    <button type="submit" class="button">Aktualisieren</button>
    <a href="{{ url_for('contact.user', handle=user.certificate.full_handle) }}" class="button secondary">Abbrechen</a>
</form>
{% endblock %}

webapp2/templates/contact/user.html
{% extends "layout/application.html" %}
{% block body %}
<a href="{{ url_for('send.index', reply_to=cert.full_handle) }}" class="button is-right-btn">Anschreiben</a>
{% if request.user.is_admin and cert.user %}
<a href="{{ url_for('contact.admin_page', id=cert.user[0].id) }}" class="button secondary is-right-btn">Einstellungen</a>
{% endif %}
<h1>{{ cert.name }}</h1>
<div class="meta">
    <div class="meta--field">
        👤 {{ cert.full_handle }}
    </div>
</div>

<h3>Informationen</h3>

<table>
    <tr>
        <th>Name</th>
        <td>{{ sec_cert.Name }}</td>
    </tr>
    <tr>
        <th>Kennung</th>
        <td>{{ sec_cert.Handle }}</td>
    </tr>
    <tr>
        <th>Hinweise</th>
        <td>
            <ul>
                {% for flag in sec_cert.Flags %}
                    {% if flag == 'verified' %}
                        <li><strong>Verifiziert.</strong> Der Anbieter hat die Identität überprüft.</li>
                    {% elif flag == 'authority' %}
                        <li><strong>Amtlich.</strong> Laut Anbieter ist dies eine Regierungsbehörde.</li>
                    {% elif flag == 'readconfirm' %}
                        <li><strong>Lesebestätigung.</strong> Der Lesestatus wird bei Nachrichten an diese Adresse angezeigt.</li>
                    {% elif flag == 'temporary' %}
                        <li><strong>Vorläufig.</strong> Dieses vorläufige Zertifikat ist nur 180 Tage gültig.</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </td>
    </tr>
    <tr>
        <th>Gültigkeit</th>
        <td>
            {% if trust_status == 'local' %}
                ✅ Das Zertifikat stammt von diesem Anbieter und ist vertrauenswürdig.
            {% elif trust_status == 'trustworthy_service' %}
                ✅ Das Zertifikat stammt von einem vertrauenswürdigen Anbieter und ist in Ordnung.
            {% elif trust_status == 'broken' %}
                ⚠️ Das Zertifikat ist gefälscht oder kann nicht überprüft werden.
            {% else %}
                🔒 Das Zertifikat ist in Ordnung, der Anbieter ist aber nicht vertrauenswürdig.
            {% endif %}
        </td>
    </tr>
</table>

<h3>Zertifikat</h3>
<pre class="cert">{{ cert.certfile_body }}</pre>
{% endblock %}